// Generated by gencpp from file random_node/Num.msg
// DO NOT EDIT!


#ifndef RANDOM_NODE_MESSAGE_NUM_H
#define RANDOM_NODE_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace random_node
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : num2(0)
    , num1(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : num2(0)
    , num1(0)  {
  (void)_alloc;
    }



   typedef int64_t _num2_type;
  _num2_type num2;

   typedef int64_t _num1_type;
  _num1_type num1;





  typedef boost::shared_ptr< ::random_node::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::random_node::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::random_node::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::random_node::Num > NumPtr;
typedef boost::shared_ptr< ::random_node::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::random_node::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::random_node::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace random_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'random_node': ['/home/jacob/src/myROS/ros_workspace/src/random_node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::random_node::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::random_node::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::random_node::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::random_node::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::random_node::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::random_node::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::random_node::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a06ab5c483fb1e429227b624b91e13d7";
  }

  static const char* value(const ::random_node::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa06ab5c483fb1e42ULL;
  static const uint64_t static_value2 = 0x9227b624b91e13d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::random_node::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "random_node/Num";
  }

  static const char* value(const ::random_node::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::random_node::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int64 num2\n\
int64 num1\n\
";
  }

  static const char* value(const ::random_node::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::random_node::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num2);
      stream.next(m.num1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::random_node::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::random_node::Num_<ContainerAllocator>& v)
  {
    s << indent << "num2: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num2);
    s << indent << "num1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RANDOM_NODE_MESSAGE_NUM_H
