// Generated by gencpp from file random_node/Num.msg
// DO NOT EDIT!


#ifndef RANDOM_NODE_MESSAGE_NUM_H
#define RANDOM_NODE_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Time.h>

namespace random_node
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : header()
    , start()
    , num2(0)
    , num1(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , start(_alloc)
    , num2(0)
    , num1(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Time_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef int16_t _num2_type;
  _num2_type num2;

   typedef int16_t _num1_type;
  _num1_type num1;





  typedef boost::shared_ptr< ::random_node::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::random_node::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::random_node::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::random_node::Num > NumPtr;
typedef boost::shared_ptr< ::random_node::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::random_node::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::random_node::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace random_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'random_node': ['/home/jacob/src/myROS/ros_workspace/src/random_node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::random_node::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::random_node::Num_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::random_node::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::random_node::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::random_node::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::random_node::Num_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::random_node::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ab4760c592fe1830e3587fa9b42e8b1";
  }

  static const char* value(const ::random_node::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ab4760c592fe183ULL;
  static const uint64_t static_value2 = 0x0e3587fa9b42e8b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::random_node::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "random_node/Num";
  }

  static const char* value(const ::random_node::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::random_node::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
std_msgs/Time start\n\
int16 num2\n\
int16 num1\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/Time\n\
time data\n\
";
  }

  static const char* value(const ::random_node::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::random_node::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.start);
      stream.next(m.num2);
      stream.next(m.num1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::random_node::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::random_node::Num_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "start: ";
    s << std::endl;
    Printer< ::std_msgs::Time_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "num2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.num2);
    s << indent << "num1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.num1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RANDOM_NODE_MESSAGE_NUM_H
